# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lighting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elighting.proto\x12\x04rero\"#\n\x0fLightingRequest\x12\x10\n\x08newState\x18\x01 \x01(\t\"\x18\n\x06Status\x12\x0e\n\x06status\x18\x01 \x01(\t2F\n\x08Lighting\x12:\n\x11GetLightingChange\x12\x15.rero.LightingRequest\x1a\x0c.rero.Status\"\x00\x62\x06proto3')



_LIGHTINGREQUEST = DESCRIPTOR.message_types_by_name['LightingRequest']
_STATUS = DESCRIPTOR.message_types_by_name['Status']
LightingRequest = _reflection.GeneratedProtocolMessageType('LightingRequest', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTINGREQUEST,
  '__module__' : 'lighting_pb2'
  # @@protoc_insertion_point(class_scope:rero.LightingRequest)
  })
_sym_db.RegisterMessage(LightingRequest)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), {
  'DESCRIPTOR' : _STATUS,
  '__module__' : 'lighting_pb2'
  # @@protoc_insertion_point(class_scope:rero.Status)
  })
_sym_db.RegisterMessage(Status)

_LIGHTING = DESCRIPTOR.services_by_name['Lighting']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LIGHTINGREQUEST._serialized_start=24
  _LIGHTINGREQUEST._serialized_end=59
  _STATUS._serialized_start=61
  _STATUS._serialized_end=85
  _LIGHTING._serialized_start=87
  _LIGHTING._serialized_end=157
# @@protoc_insertion_point(module_scope)
