# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rero_grpc.lighting_pb2 as lighting__pb2


class LightingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLightingChange = channel.unary_unary(
                '/rero.Lighting/GetLightingChange',
                request_serializer=lighting__pb2.LightingRequest.SerializeToString,
                response_deserializer=lighting__pb2.Status.FromString,
                )


class LightingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLightingChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LightingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLightingChange': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLightingChange,
                    request_deserializer=lighting__pb2.LightingRequest.FromString,
                    response_serializer=lighting__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rero.Lighting', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Lighting(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLightingChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rero.Lighting/GetLightingChange',
            lighting__pb2.LightingRequest.SerializeToString,
            lighting__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
