# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: touch.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btouch.proto\x12\x04rero\"\x1c\n\x0cTouchRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\".\n\rTouchResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\r2G\n\x05Touch\x12>\n\x11GetLightingChange\x12\x12.rero.TouchRequest\x1a\x13.rero.TouchResponse\"\x00\x62\x06proto3')



_TOUCHREQUEST = DESCRIPTOR.message_types_by_name['TouchRequest']
_TOUCHRESPONSE = DESCRIPTOR.message_types_by_name['TouchResponse']
TouchRequest = _reflection.GeneratedProtocolMessageType('TouchRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOUCHREQUEST,
  '__module__' : 'touch_pb2'
  # @@protoc_insertion_point(class_scope:rero.TouchRequest)
  })
_sym_db.RegisterMessage(TouchRequest)

TouchResponse = _reflection.GeneratedProtocolMessageType('TouchResponse', (_message.Message,), {
  'DESCRIPTOR' : _TOUCHRESPONSE,
  '__module__' : 'touch_pb2'
  # @@protoc_insertion_point(class_scope:rero.TouchResponse)
  })
_sym_db.RegisterMessage(TouchResponse)

_TOUCH = DESCRIPTOR.services_by_name['Touch']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TOUCHREQUEST._serialized_start=21
  _TOUCHREQUEST._serialized_end=49
  _TOUCHRESPONSE._serialized_start=51
  _TOUCHRESPONSE._serialized_end=97
  _TOUCH._serialized_start=99
  _TOUCH._serialized_end=170
# @@protoc_insertion_point(module_scope)
