# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rero_io_grpc.touch_pb2 as touch__pb2


class TouchStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTouchRequest = channel.unary_unary(
                '/rero.Touch/GetTouchRequest',
                request_serializer=touch__pb2.TouchRequest.SerializeToString,
                response_deserializer=touch__pb2.TouchResponse.FromString,
                )


class TouchServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTouchRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TouchServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTouchRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTouchRequest,
                    request_deserializer=touch__pb2.TouchRequest.FromString,
                    response_serializer=touch__pb2.TouchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rero.Touch', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Touch(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTouchRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rero.Touch/GetTouchRequest',
            touch__pb2.TouchRequest.SerializeToString,
            touch__pb2.TouchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
